# Generated by Django 4.0.3 on 2022-03-25 02:27

from django.db import migrations, models
import flatworks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_accessibility_lift',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_accessibility_wheelchair',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_animal_allowance',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_communal_spaces',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[flatworks.validators.validate_cost]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_furnished',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_number_of_rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
