# Generated by Django 4.0.3 on 2022-03-25 18:59

from django.db import migrations, models
import flatworks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0002_alter_property_property_accessibility_lift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_image',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=models.CharField(max_length=200, unique=True, validators=[flatworks.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_borough',
            field=models.CharField(max_length=40, null=True, validators=[flatworks.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_city',
            field=models.CharField(max_length=40, validators=[flatworks.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_country',
            field=models.CharField(max_length=40, validators=[flatworks.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
