# Generated by Django 4.0.3 on 2022-03-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0005_alter_profile_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_image',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/properties_imgs/', verbose_name=''),
        ),
    ]
