# Generated by Django 4.0.3 on 2022-03-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0009_alter_profile_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_information',
            field=models.CharField(default='not avaliable', max_length=500),
            preserve_default=False,
        ),
    ]
