# Generated by Django 4.0.3 on 2022-03-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0010_property_property_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_information',
            field=models.TextField(),
        ),
    ]
