# Generated by Django 4.0.3 on 2022-03-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0011_alter_property_property_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_information',
            field=models.TextField(blank=True),
        ),
    ]
