# Generated by Django 4.0.3 on 2022-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0012_alter_property_property_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_image',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/user_imgs/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/properties_imgs/', verbose_name=''),
        ),
    ]
