# Generated by Django 4.0.3 on 2022-03-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0017_alter_profile_image_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='property_image',
            name='name',
        ),
    ]
