# Generated by Django 4.0.3 on 2022-03-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0019_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flatworks.user')),
            ],
        ),
    ]
