# Generated by Django 4.0.3 on 2022-03-28 05:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0020_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocked_users',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='flatworks.user', verbose_name='User Blocked By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blocked_users',
            name='blocked_user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='flatworks.user', verbose_name='User Blocked'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='INTERNATIONAL'),
        ),
    ]
