# Generated by Django 4.0.3 on 2022-03-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0021_blocked_users_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocked_users',
            old_name='blocked_user_id',
            new_name='blocked_user',
        ),
        migrations.RenameField(
            model_name='blocked_users',
            old_name='user_id',
            new_name='user',
        ),
    ]
