# Generated by Django 4.0.3 on 2022-03-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0022_rename_blocked_user_id_blocked_users_blocked_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_image',
            name='property',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flatworks.property'),
        ),
    ]
