# Generated by Django 4.0.3 on 2022-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0023_alter_property_image_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_imgs/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/properties_imgs/', verbose_name=''),
        ),
    ]
