# Generated by Django 4.0.3 on 2022-03-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatworks', '0024_alter_profile_image_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_borough',
            field=models.CharField(blank=True, default='Redbridge', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_postal_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
